### PR TITLE
Add methods to get data for specific dates

### PR DESCRIPTION
**Pull request by stabbylambda**
I'm using your awesome ha-openei integration for realtime monitoring. I wanted to use the OpenEI data to analyze some of my historical utility data, but in order to do that I needed to break out methods to be able to get some rates for specific datetimes instead of always having `now`

### CODE REVIEW

**Comment by firstof9** [comment]
Mind updating the tests along with this?

**Comment by stabbylambda** [comment]
I, uh, may have forgotten a bunch of return statements. Which I blame on spending too much time in Rust. 😄

**Comment by firstof9** [comment]
Looks like those changes made the tests happy :+1:

**Comment by firstof9** [comment]
Thanks!

**Pull request merged**
